.TH SDTSDEM2XYZ 1
.SH NAME
sdtsdem2xyz \- translate USGS SDTS/DEM files into (x,y,z) format
.SH SYNOPSIS
.B sdtsdem2xyz
<SDTS CATD module>


.SH DESCRIPTION
.I  Sdtsdem2xyz
translates a USGS SDTS/DEM file into (x,y,z) coordinates.  The
coordinates are dumped to stdout.


.SH BUGS
.I Sdtsdem2xyz
hasn't been extensively tested.  Caveat emptor!


.SH WHO TO BLAME
.I Sdtsdem2xyz
was written by Mark Coletti on contract to the United States
Geological Survey from SAIC.  He can be reached at
mcoletti@lychnobite.org.
