// Copyright (c) 1999,2000,2001  Utrecht University (The Netherlands),
// ETH Zurich (Switzerland), Freie Universitaet Berlin (Germany),
// INRIA Sophia-Antipolis (France), Martin-Luther-University Halle-Wittenberg
// (Germany), Max-Planck-Institute Saarbruecken (Germany), RISC Linz (Austria),
// and Tel-Aviv University (Israel).  All rights reserved.
//
// This file is part of CGAL (www.cgal.org); you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation; version 2.1 of the License.
// See the file LICENSE.LGPL distributed with CGAL.
//
// Licensees holding a valid commercial license may use this file in
// accordance with the commercial license agreement provided with the software.
//
// This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
// WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// $Source: /CVSROOT/CGAL/Packages/Interval_arithmetic/include/CGAL/Arithmetic_filter/static_infos/predicates/Regular_triangulation_rtH2.h,v $
// $Revision: 1.12 $ $Date: 2003/10/21 12:17:37 $
// $Name: current_submission $
//
// Author(s)     : Sylvain Pion <Sylvain.Pion@sophia.inria.fr>

// This file is automatically generated by
// scripts/filtered_predicates_generator.pl

#ifndef CGAL_ARITHMETIC_FILTER_REGULAR_TRIANGULATION_RTH2_H_STATIC_INFO_H
#define CGAL_ARITHMETIC_FILTER_REGULAR_TRIANGULATION_RTH2_H_STATIC_INFO_H

#include <CGAL/Profile_counter.h>

double Static_Filtered_power_testH2_16::_epsilon_0;
double Static_Filtered_power_testH2_16::_bound = -1.0;

double Static_Filtered_power_testH2_12::_epsilon_0;
double Static_Filtered_power_testH2_12::_epsilon_1;
double Static_Filtered_power_testH2_12::_bound = -1.0;

#endif // CGAL_ARITHMETIC_FILTER_REGULAR_TRIANGULATION_RTH2_H_STATIC_INFO_H
