# file: Makefile (for inc)
#	CORE Library version 1.4
#	$Id: Makefile,v 1.1 2003/06/22 10:50:10 afabri Exp $

# =============================================================
# PATHS =======================================================
# =============================================================

CORE_PATH=..

INCLUDE=-I${CORE_PATH}/inc

LIBPATH= 

save:
	-mkdir RCS; ci -l -m"make save" *.h Makefile*

clean:

veryclean: clean
