#ifndef WED_UIDEFS_H
#define WED_UIDEFS_H

enum {
	FILE_DIALOG_NEW_PROJECT = 1,
	FILE_DIALOG_OPEN_PROJECT,
	FILE_DIALOG_PICK_IMAGE_OVERLAY,
	FILE_DIALOG_EXPORT_APTDAT,
	FILE_DIALOG_IMPORT_APTDAT,
	FILE_DIALOG_PICK_XSYSTEM
};

#define	BEZ_MIN_SEGS		3
#define BEZ_MAX_SEGS		100
#define	BEZ_PIX_PER_SEG		10

#endif
