.TH TOMKSDTS 1
.SH NAME
tomksdts \-   Create mksdts(1) file from SDTS modules
.SH SYNOPSIS
.B tomksdts
[-v] SDTS module
.SH OPTIONS
.TP
.B \-v
Toggle on noisy output


.SH DESCRIPTION
.I  Tomksdts
Converts an SDTS module into a SDTS Definition Language (SDL) text
file to stdout.  SDL is described in mksdts(1).

.SH SEE ALSO
mksdts(1).

.SH BUGS
.I Tomksdts
hasn't been extensively tested.  Caveat emptor!

Also, it doesn't (yet) support SDTS modules with binary data.


.SH WHO TO BLAME
.I Tomksdts
was written by Mark Coletti on contract to the United States Geological
Survey from SAIC.  He can be reached at mcoletti@lychnobite.org .
