#!/bin/sh
#
# wrapper for sb_Comp test
#
# $Id: sh_Comp_t,v 1.2 2002/10/10 20:35:25 mcoletti Exp $

sample_comp=abcdcomp.ddf;       # COMP module included for test purposes

if [ -r ./${sample_comp} ]; then
    ./sb_comp_t $sample_comp > /dev/null;

                                # bail on failure
    if [ $? -ne 0 ]; then exit 1; fi

else                            # XXX obviously temporary
    echo ${sample_comp} missing ... skipping COMP module test;
    exit 0;
fi

exit 0
