Title: WorldEditor Manual
HTML header: <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script><script src="https://developer.x-plane.com/manuals/assets/js/manual.js"></script>
HTML footer: </div>
CSS: https://developer.x-plane.com/manuals/assets/css/markdown.css

<div id="manual_wrapper">
<nav id="toc_container">
<h2>Table of Contents</h2>

{{TOC:2-5}}

</nav>

