ENUM_DOMAIN(Airport_Type, "Airport Type")
	ENUM(type_Airport,	"Airport", 1)
	ENUM(type_Seaport,	"Seaport", 16)
	ENUM(type_Heliport,	"Heliport",17)

ENUM_DOMAIN(Edge_Lights, "Runway Edge Light Types")
	
	ENUM(edge_None, "None", 0)
//	ENUM(edge_LIRL, "LIRL", 1)
	ENUM(edge_MIRL,	"MIRL",	2)
//	ENUM(edge_HIRL,	"HIRL", 3)

ENUM_DOMAIN(REIL_Lights,"Runway End Identifier Lights")
	ENUM(reil_None,"None",0)
	ENUM(reil_Omni,"Omnidirectional REIL", 1)
	ENUM(reil_Uni,"Unidirectional REIL",2)
	
ENUM_DOMAIN(Heli_Lights,"Helipad Edge Lights")
	ENUM(heli_None,"None",0)
	ENUM(heli_Yellow,"Yellow",1)
//	ENUM(heli_White,"White", 2)
//	ENUM(heli_Red,"Red",3)

ENUM_DOMAIN(Sign_Size,"Sign Size")
	ENUM(size_SmallTaxi,"Small Taxiway", 1)
	ENUM(size_MediumTaxi,"Medium Taxiway", 2)
	ENUM(size_LargeTaxi,"Large Taxiway", 3)
	ENUM(size_LargeRemaining,"Large Distance Remaining",4)
	ENUM(size_SmallRemaining,"Small Distance Remaining", 5)

ENUM_DOMAIN(Sign_Style,"Sign Style")
	ENUM(style_Default,"Default",0)

ENUM_DOMAIN(Surface_Type,"Surface Type")
	ENUM(surf_Asphalt,"Asphalt",1)
	ENUM(surf_Concrete,"Concrete",2)
	ENUM(surf_Grass,"Grass",3)
	ENUM(surf_Dirt,"Dirt",4)
	ENUM(surf_Gravel,"Gravel",5)
	ENUM(surf_Lake,"Dry Lakebed",12)
	ENUM(surf_Water,"Water",13)
	ENUM(surf_Snow,"Snow",14)
	ENUM(surf_Trans,"Transparent",15)
	
ENUM_DOMAIN(Light_Fixt,"Light Fixtures")
	ENUM(light_VASI,"VASI", 1)
	ENUM(light_PAPI_Left,"PAPI (Left Side)",2)
	ENUM(light_PAPI_Right,"PAPI (Right Side)",3)
	ENUM(light_PAPI20,"PAPI (20 degrees)",4)
	ENUM(light_VASI_Tri,"VASI (Tri-Color)",5)
	ENUM(light_WigWag,"Wig-Wags",6)

ENUM_DOMAIN(Light_App,"Approach Lights")
	ENUM(app_None,		"None",						0)
	ENUM(app_ALSFI,		"ALSF-I",					1)
	ENUM(app_ALSFII,	"ALSF-II",					2)
	ENUM(app_Calvert,	"Calvert",					3)
	ENUM(app_Calvert2,	"Calvert-II",				4)

	ENUM(app_SSALR,		"SSALR",					5)
	ENUM(app_SSALF,		"SSALF",					6)
	ENUM(app_SALS,		"SALS",						7)	

	ENUM(app_MALSR,		"MALSR",					8)
	ENUM(app_MALSF,		"MALSF",					9)
	ENUM(app_MALS,		"MALS",						10)

	ENUM(app_ODALS,		"ODALS",					11)
	ENUM(app_RAIL,		"RAIL",						12)
	
ENUM_DOMAIN(Shoulder_Type,"Shoulder Type")
	ENUM(shoulder_None,			"None",				0)
	ENUM(shoulder_Asphalt,		"Asphalt",			1)
	ENUM(shoulder_Concrete,		"Concrete",			1)	
	
ENUM_DOMAIN(Runway_Markings,"Runway Markings")
	ENUM(mark_None,				"None",						0)
	ENUM(mark_Visual,			"Visual",					1)
	ENUM(mark_NonPrecis,		"Non-Precision (US)",		2)
	ENUM(mark_Precis,			"Precision (US)",			3)
	ENUM(mark_NonPrecisUK,		"Non-Precision (UK)",		4)
	ENUM(mark_PrecisUK,			"Precision (UK)",			5)

ENUM_DOMAIN(Helipad_Markings,"Helipad Markings")
	ENUM(heli_Mark_Default,		"Default",					0)
	
ENUM_DOMAIN(Airport_Beacon,"Airport Beacon Type")
	ENUM(beacon_Airport,		"Airport",					1)
	ENUM(beacon_Seaport,		"Seaport",					2)
	ENUM(beacon_Heliport,		"Heliport",					3)
	ENUM(beacon_MilitaryAirport,"Military Airport",			4)

ENUM_DOMAIN(LinearFeature, "Linear Markings")
	ENUM(line_SolidYellow,		"Solid Yellow",					1)
	ENUM(line_BrokenYellow,		"Broken Yellow",				2)
	ENUM(line_DoubleSolidYellow,"Double Solid Yellow",			3)
	ENUM(line_RunwayHold,		"Runway Hold",					4)
	ENUM(line_OtherHold,		"Other Hold",					5)
	ENUM(line_ILSHold,			"ILS Hold",						6)
	ENUM(line_ILSCriticalCenter,"ILS Critical Centerline",		7)
	ENUM(line_WideBrokenSingle,	"Wide Broken Single Yellow",	8)
	ENUM(line_WideBrokenDouble,	"Wide Broken Double Yellow",	9)

	ENUM(line_SolidWhite,		"Solid White (Roadway)",				20)
	ENUM(line_Chequered,		"Chequered White (Roadway)",			21)
	ENUM(line_BrokenWhite,		"Broken White (Roadway)",				22)

	ENUM(line_BSolidYellow,		"Solid Yellow (Black)",					51)
	ENUM(line_BBrokenYellow,	"Broken Yellow (Black)",				52)
	ENUM(line_BDoubleSolidYellow,"Double Solid Yellow (Black)",			53)
	ENUM(line_BRunwayHold,		"Runway Hold (Black)",					54)
	ENUM(line_BOtherHold,		"Other Hold (Black)",					55)
	ENUM(line_BILSHold,			"ILS Hold (Black)",						56)
	ENUM(line_BILSCriticalCenter,"ILS Critical Centerline (Black)",		57)
	ENUM(line_BWideBrokenSingle,"Wide Broken Single Yellow (Black)",	58)
	ENUM(line_BWideBrokenDouble,"Wide Broken Double Yellow (Black)",	59)

	ENUM(line_TaxiCenter,		"Taxiway Centerline Lights (Green)",	101)
	ENUM(line_TaxiEdge,			"Taxiway Edge Lights (Blue)",			102)
	ENUM(line_HoldLights,		"Hold Short Lights (Amber)",			103)
	ENUM(line_HoldLightsPulse,	"Hold Short Lights (Pulsing Amber)",	104)	
	ENUM(line_HoldShortCenter,	"Hold Short Centerline Lights (Amber/Green)",105)
	ENUM(line_BoundaryEdge,		"Boundary Edge Lights (Red)",			106)
