/*
 * Copyright (c) 2007, Laminar Research.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

ENUM_DOMAIN(Airport_Type, "Airport Type")
	ENUM(type_Airport,	"Airport", apt_airport)
	ENUM(type_Heliport,	"Heliport",apt_heliport)
	ENUM(type_Seaport,	"Seaport", apt_seaport)

ENUM_DOMAIN(Edge_Lights, "Runway Edge Light Types")

	ENUM(edge_None, "None", apt_edge_none)
	ENUM(edge_LIRL, "LIRL", apt_edge_LIRL)
	ENUM(edge_MIRL,	"MIRL",	apt_edge_MIRL)
	ENUM(edge_HIRL,	"HIRL", apt_edge_HIRL)

ENUM_DOMAIN(REIL_Lights,"Runway End Identifier Lights")
	ENUM(reil_None,"None",apt_reil_none)
	ENUM(reil_Omni,"Omnidirectional REIL", apt_reil_omni)
	ENUM(reil_Uni,"Unidirectional REIL",apt_reil_uni)

ENUM_DOMAIN(Heli_Lights,"Helipad Edge Lights")
	ENUM(heli_None,"None",apt_heli_edge_none)
	ENUM(heli_Yellow,"Yellow",apt_heli_edge_yellow)
//	ENUM(heli_White,"White", 2)
//	ENUM(heli_Red,"Red",3)

ENUM_DOMAIN(Sign_Size,"Sign Size")
	ENUM(size_SmallTaxi,"Small Taxiway", apt_sign_small)
	ENUM(size_MediumTaxi,"Medium Taxiway", apt_sign_medium)
	ENUM(size_LargeTaxi,"Large Taxiway", apt_sign_large)
	ENUM(size_LargeRemaining,"Large Distance Remaining",apt_sign_large_distance)
	ENUM(size_SmallRemaining,"Small Distance Remaining", apt_sign_small_distance)

ENUM_DOMAIN(Sign_Style,"Sign Style")
	ENUM(style_Default,"Default",apt_sign_style_default)

ENUM_DOMAIN(Surface_Type,"Surface Type")
	ENUM(surf_Asphalt,"Asphalt",apt_surf_asphalt)
	ENUM(surf_Concrete,"Concrete",apt_surf_concrete)
	ENUM(surf_Grass,"Grass",apt_surf_grass)
	ENUM(surf_Dirt,"Dirt",apt_surf_dirt)
	ENUM(surf_Gravel,"Gravel",apt_surf_gravel)
	ENUM(surf_Lake,"Dry Lakebed",apt_surf_dry_lake)
	ENUM(surf_Water,"Water",apt_surf_water)
	ENUM(surf_Snow,"Snow",apt_surf_ice)
	ENUM(surf_Trans,"Transparent",apt_surf_transparent)

ENUM_DOMAIN(Light_Fixt,"Light Fixtures")
	ENUM(light_VASI,"VASI", apt_gls_vasi)
	ENUM(light_PAPI_Left,"PAPI (Left Side)",apt_gls_papi_left)
	ENUM(light_PAPI_Right,"PAPI (Right Side)",apt_gls_papi_right)
	ENUM(light_PAPI20,"PAPI (20 degrees)",apt_gls_papi_20)
	ENUM(light_VASI_Tri,"VASI (Tri-Color)",apt_gls_vasi_tricolor)
	ENUM(light_WigWag,"Wig-Wags",apt_gls_wigwag)

ENUM_DOMAIN(Light_App,"Approach Lights")
	ENUM(app_None,		"None",						apt_app_none)
	ENUM(app_ALSFI,		"ALSF-I",					apt_app_ALSFI)
	ENUM(app_ALSFII,	"ALSF-II",					apt_app_ALSFII)
	ENUM(app_Calvert,	"Calvert",					apt_app_CALVERTI)
	ENUM(app_Calvert2,	"Calvert-II",				apt_app_CALVERTII)

	ENUM(app_SSALR,		"SSALR",					apt_app_SSALR)
	ENUM(app_SSALF,		"SSALF",					apt_app_SSALF)
	ENUM(app_SALS,		"SALS",						apt_app_SALS)

	ENUM(app_MALSR,		"MALSR",					apt_app_MALSR)
	ENUM(app_MALSF,		"MALSF",					apt_app_MALSF)
	ENUM(app_MALS,		"MALS",						apt_app_MALS)

	ENUM(app_ODALS,		"ODALS",					apt_app_ODALS)
	ENUM(app_RAIL,		"RAIL",						apt_app_RAIL)

ENUM_DOMAIN(Shoulder_Type,"Shoulder Type")
	ENUM(shoulder_None,			"None",				apt_shoulder_none)
	ENUM(shoulder_Asphalt,		"Asphalt",			apt_shoulder_asphalt)
	ENUM(shoulder_Concrete,		"Concrete",			apt_shoulder_concrete)

ENUM_DOMAIN(Runway_Markings,"Runway Markings")
	ENUM(mark_None,				"None",						apt_mark_none)
	ENUM(mark_Visual,			"Visual",					apt_mark_visual)
	ENUM(mark_NonPrecis,		"Non-Precision (US)",		apt_mark_non_precision)
	ENUM(mark_Precis,			"Precision (US)",			apt_mark_precision)
	ENUM(mark_NonPrecisUK,		"Non-Precision (UK)",		apt_mark_non_precision_UK)
	ENUM(mark_PrecisUK,			"Precision (UK)",			apt_mark_precision_UK)

ENUM_DOMAIN(Helipad_Markings,"Helipad Markings")
	ENUM(heli_Mark_Default,		"Default",					apt_mark_heli_default)

ENUM_DOMAIN(Airport_Beacon,"Airport Beacon Type")
	ENUM(beacon_Airport,		"Airport",					apt_beacon_airport)
	ENUM(beacon_Seaport,		"Seaport",					apt_beacon_seaport)
	ENUM(beacon_Heliport,		"Heliport",					apt_beacon_heliport)
	ENUM(beacon_MilitaryAirport,"Military Airport",			apt_beacon_military)

ENUM_DOMAIN(LinearFeature, "Linear Markings")
	ENUM(line_SolidYellow,		"Solid Yellow",					apt_line_solid_yellow)
	ENUM(line_BrokenYellow,		"Broken Yellow",				apt_line_broken_yellow)
	ENUM(line_DoubleSolidYellow,"Double Solid Yellow",			apt_line_double_solid_yellow)
	ENUM(line_RunwayHold,		"Runway Hold",					apt_line_runway_hold)
	ENUM(line_OtherHold,		"Other Hold",					apt_line_other_hold)
	ENUM(line_ILSHold,			"ILS Hold",						apt_line_ils_hold)
	ENUM(line_ILSCriticalCenter,"ILS Critical Centerline",		apt_line_ils_center)
	ENUM(line_WideBrokenSingle,	"Wide Broken Single Yellow",	apt_line_wide_broken_yellow)
	ENUM(line_WideBrokenDouble,	"Wide Broken Double Yellow",	apt_line_wide_double_broken_yellow)

	ENUM(line_SolidWhite,		"Solid White (Roadway)",				apt_line_solid_white)
	ENUM(line_Chequered,		"Chequered White (Roadway)",			apt_line_chequered_white)
	ENUM(line_BrokenWhite,		"Broken White (Roadway)",				apt_line_broken_white)

	ENUM(line_BSolidYellow,		"Solid Yellow (Black)",					apt_line_Bsolid_yellow)
	ENUM(line_BBrokenYellow,	"Broken Yellow (Black)",				apt_line_Bbroken_yellow)
	ENUM(line_BDoubleSolidYellow,"Double Solid Yellow (Black)",			apt_line_Bdouble_solid_yellow)
	ENUM(line_BRunwayHold,		"Runway Hold (Black)",					apt_line_Brunway_hold)
	ENUM(line_BOtherHold,		"Other Hold (Black)",					apt_line_Bother_hold)
	ENUM(line_BILSHold,			"ILS Hold (Black)",						apt_line_Bils_hold)
	ENUM(line_BILSCriticalCenter,"ILS Critical Centerline (Black)",		apt_line_Bils_center)
	ENUM(line_BWideBrokenSingle,"Wide Broken Single Yellow (Black)",	apt_line_Bwide_broken_yellow)
	ENUM(line_BWideBrokenDouble,"Wide Broken Double Yellow (Black)",	apt_line_Bwide_double_broken_yellow)

	ENUM(line_TaxiCenter,		"Taxiway Centerline Lights (Green)",	apt_light_taxi_centerline)
	ENUM(line_TaxiEdge,			"Taxiway Edge Lights (Blue)",			apt_light_taxi_edge)
	ENUM(line_HoldLights,		"Hold Short Lights (Amber)",			apt_light_hold_short)
	ENUM(line_HoldLightsPulse,	"Hold Short Lights (Pulsing Amber)",	apt_light_hold_short_flash)
	ENUM(line_HoldShortCenter,	"Hold Short Centerline Lights (Amber/Green)",apt_light_hold_short_centerline)
	ENUM(line_BoundaryEdge,		"Boundary Edge Lights (Red)",			apt_light_bounary)

ENUM_DOMAIN(ATCFrequency, "ATC Frequency")
	ENUM(atc_AWOS,				"AWOS",									apt_freq_awos)
	ENUM(atc_CTAF,				"CTAF",									apt_freq_ctaf)
	ENUM(atc_Delivery,			"Clearance Delivery",					apt_freq_del)
	ENUM(atc_Ground,			"Ground Control",						apt_freq_gnd)
	ENUM(atc_Tower,				"Tower",								apt_freq_twr)
	ENUM(atc_Approach,			"Approach",								apt_freq_app)
	ENUM(atc_Departure,			"Departure",							apt_freq_dep)

ENUM_DOMAIN(ExclusionTypes, "Exclusion Types")
	ENUM(exclude_Obj,			"Objects",								0)
	ENUM(exclude_Fac,			"Facades",								1)
	ENUM(exclude_For,			"Forests",								2)
	ENUM(exclude_Bch,			"Beaches",								3)
	ENUM(exclude_Net,			"Road Networks",						4)
	ENUM(exclude_Lin,			"Lines",								5)
	ENUM(exclude_Pol,			"Draped Polygons",						6)
	ENUM(exclude_Str,			"String",								7)

ENUM_DOMAIN(TCE_GridSnap, "Grid")
	ENUM(tce_Grid_None,				"None",								0)
	ENUM(tce_Grid_Whole,			"1",								1)
	ENUM(tce_Grid_Half,				"1/2",								2)		
	ENUM(tce_Grid_Quarter,			"1/4",								3)
	
	
ENUM_DOMAIN(ATCPatternSide,"Pattern Side")
	ENUM(atc_Left,					"Left",								apt_pattern_left)
	ENUM(atc_Right,					"Right",							apt_pattern_right)		

ENUM_DOMAIN(ATCTrafficType,"Traffic Type")
	ENUM(atc_Heavies,				"Heavy Jets",						atc_traffic_heavies)
	ENUM(atc_Jets,					"Jets",								atc_traffic_jets)
	ENUM(atc_Props,					"Props",							atc_traffic_props)	
	ENUM(atc_Helicopters,			"Helicopters",						atc_traffic_helis)		
	
ENUM_DOMAIN(ATCOperationType,"Operations")
	ENUM(atc_Arrivals,				"Arrivals",							atc_op_arrivals)
	ENUM(atc_Departures,			"Departures",						atc_op_departures)

ENUM_DOMAIN(ATCRunwayName,"Runway")
	ENUM(atc_Runway_None,				"None",		0)
	ENUM(atc_1,							"01",		10)
	ENUM(atc_1L,						"01L",		11)
	ENUM(atc_1C,						"01C",		12)
	ENUM(atc_1R,						"01R",		13)
	ENUM(atc_2,							"02",		20)
	ENUM(atc_2L,						"02L",		21)
	ENUM(atc_2C,						"02C",		22)
	ENUM(atc_2R,						"02R",		23)
	ENUM(atc_3,							"03",		30)
	ENUM(atc_3L,						"03L",		31)
	ENUM(atc_3C,						"03C",		32)
	ENUM(atc_3R,						"03R",		33)
	ENUM(atc_4,							"04",		40)
	ENUM(atc_4L,						"04L",		41)
	ENUM(atc_4C,						"04C",		42)
	ENUM(atc_4R,						"04R",		43)
	ENUM(atc_5,							"05",		50)
	ENUM(atc_5L,						"05L",		51)
	ENUM(atc_5C,						"05C",		52)
	ENUM(atc_5R,						"05R",		53)
	ENUM(atc_6,							"06",		60)
	ENUM(atc_6L,						"06L",		61)
	ENUM(atc_6C,						"06C",		62)
	ENUM(atc_6R,						"06R",		63)
	ENUM(atc_7,							"07",		70)
	ENUM(atc_7L,						"07L",		71)
	ENUM(atc_7C,						"07C",		72)
	ENUM(atc_7R,						"07R",		73)
	ENUM(atc_8,							"08",		80)
	ENUM(atc_8L,						"08L",		81)
	ENUM(atc_8C,						"08C",		82)
	ENUM(atc_8R,						"08R",		83)
	ENUM(atc_9,							"09",		90)
	ENUM(atc_9L,						"09L",		91)
	ENUM(atc_9C,						"09C",		92)
	ENUM(atc_9R,						"09R",		93)
	ENUM(atc_10,						"10",		100)
	ENUM(atc_10L,						"10L",		101)
	ENUM(atc_10C,						"10C",		102)
	ENUM(atc_10R,						"10R",		103)
	ENUM(atc_11,						"11",		110)
	ENUM(atc_11L,						"11L",		111)
	ENUM(atc_11C,						"11C",		112)
	ENUM(atc_11R,						"11R",		113)
	ENUM(atc_12,						"12",		120)
	ENUM(atc_12L,						"12L",		121)
	ENUM(atc_12C,						"12C",		122)
	ENUM(atc_12R,						"12R",		123)
	ENUM(atc_13,						"13",		130)
	ENUM(atc_13L,						"13L",		131)
	ENUM(atc_13C,						"13C",		132)
	ENUM(atc_13R,						"13R",		133)
	ENUM(atc_14,						"14",		140)
	ENUM(atc_14L,						"14L",		141)
	ENUM(atc_14C,						"14C",		142)
	ENUM(atc_14R,						"14R",		143)
	ENUM(atc_15,						"15",		150)
	ENUM(atc_15L,						"15L",		151)
	ENUM(atc_15C,						"15C",		152)
	ENUM(atc_15R,						"15R",		153)
	ENUM(atc_16,						"16",		160)
	ENUM(atc_16L,						"16L",		161)
	ENUM(atc_16C,						"16C",		162)
	ENUM(atc_16R,						"16R",		163)
	ENUM(atc_17,						"17",		170)
	ENUM(atc_17L,						"17L",		171)
	ENUM(atc_17C,						"17C",		172)
	ENUM(atc_17R,						"17R",		173)
	ENUM(atc_18,						"18",		180)
	ENUM(atc_18L,						"18L",		181)
	ENUM(atc_18C,						"18C",		182)
	ENUM(atc_18R,						"18R",		183)
	ENUM(atc_19,						"19",		190)
	ENUM(atc_19L,						"19L",		191)
	ENUM(atc_19C,						"19C",		192)
	ENUM(atc_19R,						"19R",		193)
	ENUM(atc_20,						"20",		200)
	ENUM(atc_20L,						"20L",		201)
	ENUM(atc_20C,						"20C",		202)
	ENUM(atc_20R,						"20R",		203)
	ENUM(atc_21,						"21",		210)
	ENUM(atc_21L,						"21L",		211)
	ENUM(atc_21C,						"21C",		212)
	ENUM(atc_21R,						"21R",		213)
	ENUM(atc_22,						"22",		220)
	ENUM(atc_22L,						"22L",		221)
	ENUM(atc_22C,						"22C",		222)
	ENUM(atc_22R,						"22R",		223)
	ENUM(atc_23,						"23",		230)
	ENUM(atc_23L,						"23L",		231)
	ENUM(atc_23C,						"23C",		232)
	ENUM(atc_23R,						"23R",		233)
	ENUM(atc_24,						"24",		240)
	ENUM(atc_24L,						"24L",		241)
	ENUM(atc_24C,						"24C",		242)
	ENUM(atc_24R,						"24R",		243)
	ENUM(atc_25,						"25",		250)
	ENUM(atc_25L,						"25L",		251)
	ENUM(atc_25C,						"25C",		252)
	ENUM(atc_25R,						"25R",		253)
	ENUM(atc_26,						"26",		260)
	ENUM(atc_26L,						"26L",		261)
	ENUM(atc_26C,						"26C",		262)
	ENUM(atc_26R,						"26R",		263)
	ENUM(atc_27,						"27",		270)
	ENUM(atc_27L,						"27L",		271)
	ENUM(atc_27C,						"27C",		272)
	ENUM(atc_27R,						"27R",		273)
	ENUM(atc_28,						"28",		280)
	ENUM(atc_28L,						"28L",		281)
	ENUM(atc_28C,						"28C",		282)
	ENUM(atc_28R,						"28R",		283)
	ENUM(atc_29,						"29",		290)
	ENUM(atc_29L,						"29L",		291)
	ENUM(atc_29C,						"29C",		292)
	ENUM(atc_29R,						"29R",		293)
	ENUM(atc_30,						"30",		300)
	ENUM(atc_30L,						"30L",		301)
	ENUM(atc_30C,						"30C",		302)
	ENUM(atc_30R,						"30R",		303)
	ENUM(atc_31,						"31",		310)
	ENUM(atc_31L,						"31L",		311)
	ENUM(atc_31C,						"31C",		312)
	ENUM(atc_31R,						"31R",		313)
	ENUM(atc_32,						"32",		320)
	ENUM(atc_32L,						"32L",		321)
	ENUM(atc_32C,						"32C",		322)
	ENUM(atc_32R,						"32R",		323)
	ENUM(atc_33,						"33",		330)
	ENUM(atc_33L,						"33L",		331)
	ENUM(atc_33C,						"33C",		332)
	ENUM(atc_33R,						"33R",		333)
	ENUM(atc_34,						"34",		340)
	ENUM(atc_34L,						"34L",		341)
	ENUM(atc_34C,						"34C",		342)
	ENUM(atc_34R,						"34R",		343)
	ENUM(atc_35,						"35",		350)
	ENUM(atc_35L,						"35L",		351)
	ENUM(atc_35C,						"35C",		352)
	ENUM(atc_35R,						"35R",		353)
	ENUM(atc_36,						"36",		360)
	ENUM(atc_36L,						"36L",		361)
	ENUM(atc_36C,						"36C",		362)
	ENUM(atc_36R,						"36R",		363)

