.TH 3ds2m 1 "12 Jan 2001" Version 1.0
.SH NAME
3ds2m - Converts meshes of a 3DS file into a m-file.
.SH SYNOPSIS
.B 3ds2m
[options] filename [options]
.SH DESCRIPTION
.PP
\fI3ds2m\fP is a tool to convert meshes of a 3DS file into a m-file. 
.SH OPTIONS
.l
\fI3ds2m\fP accepts the following options:
.TP 8
.B -h/--help
This help
.TP 8
.B -o/--output <filename>
Write output to <filename> instead of stdout
.TP 8
.B -m/--mesh name
Write only specific mesh.B -c/--camera <name>
.SH COPYRIGHT
3ds2m Copyright \(co 1996-2001 by J.E. Hoffmann <je-h@gmx.net>
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

