name: scp WED build to dev.x-plane

on:
  workflow_dispatch:
    inputs:
      ver_string:
        type: string
        description: 'Release name, must be exactly 3 digits + letter + digit'
        default: '250b0'
        required: true

jobs:
  build:
    name: scp WED files to dev.x-plane.com
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: wed_release_build
      - name: Show them
        run: |
          echo "Releasing ${{ inputs.ver_string }}"
          ls -lR .
      - name: Build zip files
        run: |
          chmod -Rc a+x build
          zip -jr wed_lin_${{ inputs.ver_string }} src build/Linux
          zip -jr wed_win_${{ inputs.ver_string }} src msvc
          cp src/WEDCore/README.WorldEditor .
          mv build/WED.xcache/Products/Applications/WED.app .
          zip    wed_mac_${{ inputs.ver_string }} README.WorldEditopr WED.app
      - name: Upload zipfiles
        uses: actions/upload-artifact@v3
        with:
          name: wed_zipfiles
          path: ./*.zip

